export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CLEAR_BANNED_USERS = 'CLEAR_BANNED_USERS';
export const ADD_BANNED_USER_START = 'ADD_BANNED_USER_START';
export const ADD_BANNED_USER_SUCCESS = 'ADD_BANNED_USER_SUCCESS';
export const ADD_BANNED_USER_FAILURE = 'ADD_BANNED_USER_FAILURE';
export const GET_BANNED_USERS_START = 'GET_BANNED_USERS_START';
export const GET_BANNED_USERS_SUCCESS = 'GET_BANNED_USERS_SUCCESS';
export const GET_BANNED_USERS_FAILURE = 'GET_BANNED_USERS_FAILURE';
export const GET_BANNED_USER_BY_NAME = 'GET_BANNED_USER_BY_NAME';
export const GET_BANNED_USER_BY_NAME_ERROR = 'GET_BANNED_USER_BY_NAME_ERROR';

export const REMOVE_FROM_BANNED_LIST_START = 'REMOVE_FROM_BANNED_LIST_START';
export const REMOVE_FROM_BANNED_LIST_SUCCESS =
  'REMOVE_FROM_BANNED_LIST_SUCCESS';
export const REMOVE_FROM_BANNED_LIST_FAILURE =
  'REMOVE_FROM_BANNED_LIST_FAILURE';
